---
- hosts: all
  becomes: yes
  tasks:

   - name: i want to install apache2 webserver 
     apt:
      name: apache2
      state: present
     
   - name: i want to start the webserver
     service:
      name: apache2
      state: started